spring:
  #  配置数据库连接池
  datasource:
    url: jdbc:mysql://106.55.36.161:3306/university?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 18438004514lzm.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  codec:
    max-in-memory-size: 100MB
    # 格式化全局时间字段
  jackson:
    date-format: yyyy年MM月dd日 HH:mm:ss
    time-zone: GMT+8



  thymeleaf:
    enabled: false
  #    配置redis
  redis:
    host: localhost
    password: 18438004514lzm.
    port: 6380
    database: 1
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  type-aliases-package: com.zzuli.gaokao.bean

# 配置MyBatis日志
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      update-strategy: NOT_NULL
  type-aliases-package: com.zzuli.gaokao.bean




  #配置community
gaokao:
  path:
      domain: http://106.55.36.161:8889/pic/
      upload-path: /opt/pic
      cf-path: /opt/cf.txt
  loadPath: ./src/main/resources/ok.txt
server:
  max-http-header-size: 128KB
